# Generated by Django 4.1.7 on 2023-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sf', models.FloatField()),
                ('location', models.TextField()),
                ('bhk', models.IntegerField()),
                ('furn_status', models.TextField()),
                ('age_of_prop', models.IntegerField()),
                ('ty_of_prop', models.TextField()),
                ('gender', models.TextField()),
            ],
        ),
    ]
